version: '3.7'
services:
  godev-build:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: build
    container_name: godev-build
    tty: true
    env_file:
      - .env.local
    environment:
      ENV: "${ENV:-development}"