#!/bin/sh

set -x

rm -rf ~/.ssh/known_hosts
if [[ "$1" == "build" ]]; then
  docker-compose -f ../docker-compose-build.yml up -d --build --remove-orphans
else
  # dev environment.
  docker-compose up -d --build
  docker-compose exec gosandbox sql-migrate up --dryrun
  docker-compose exec gosandbox sql-migrate up
fi
